import type { Metadata } from "next";
import "@/src/styles/themes.css";
import "@/src/styles/globals.css";
import ThemeContainer from "../components/ThemeContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeContainer>{children}</ThemeContainer>
      </body>
    </html>
  );
}
